package handle

import (
	"archive/zip"
	"bytes"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"net/url"
	"path"
	"regexp"
	"sort"
	"strings"

	g "gin-blog/internal/global"
	"gin-blog/internal/model"
	"gin-blog/internal/utils/upload"

	"github.com/gin-gonic/gin"
)

const (
	maxFeishuArchiveSize       = 100 << 20 // 100 MiB compressed archive
	maxFeishuArchiveFiles      = 1000
	maxFeishuArchiveContent    = 200 << 20 // guards against zip bombs
	maxFeishuImportedImageSize = 10 << 20  // 10 MiB per image
)

var (
	markdownImagePattern   = regexp.MustCompile(`!\[[^\]]*\]\((?:<)?([^\s)>]+)(?:>)?(?:\s+[^)]*)?\)`)
	archiveImageExtensions = map[string]struct{}{
		".avif": {}, ".gif": {}, ".jpeg": {}, ".jpg": {}, ".png": {}, ".webp": {},
	}
)

type feishuImportFailure struct {
	Path   string `json:"path"`
	Reason string `json:"reason"`
}

type feishuImportResult struct {
	ArticleID      int                   `json:"article_id"`
	FailedImages   []feishuImportFailure `json:"failed_images"`
	UploadedImages int                   `json:"uploaded_images"`
}

// ImportFeishuArchive imports the zip folder generated by Feishu's Markdown
// export. It intentionally saves a draft even when a subset of image uploads
// fail, so the editor can repair the remaining references.
func (*Article) ImportFeishuArchive(c *gin.Context) {
	title := strings.TrimSpace(c.PostForm("title"))
	categoryName := strings.TrimSpace(c.PostForm("category_name"))
	if title == "" || categoryName == "" {
		ReturnError(c, g.ErrRequest, "文章标题和分类不能为空")
		return
	}
	if len([]rune(title)) > 100 {
		ReturnError(c, g.ErrRequest, "文章标题不能超过 100 个字符")
		return
	}

	var tagNames []string
	if err := json.Unmarshal([]byte(c.PostForm("tag_names")), &tagNames); err != nil || len(tagNames) == 0 {
		ReturnError(c, g.ErrNoTag, "请至少选择一个标签")
		return
	}
	for index, tagName := range tagNames {
		tagNames[index] = strings.TrimSpace(tagName)
		if tagNames[index] == "" {
			ReturnError(c, g.ErrNoTag, "标签不能为空")
			return
		}
	}

	_, fileHeader, err := c.Request.FormFile("file")
	if err != nil {
		ReturnError(c, g.ErrFileReceive, err)
		return
	}
	if !strings.HasSuffix(strings.ToLower(fileHeader.Filename), ".zip") || fileHeader.Size <= 0 || fileHeader.Size > maxFeishuArchiveSize {
		ReturnError(c, g.ErrFileReceive, "请上传不超过 100 MiB 的飞书 Markdown ZIP 文件")
		return
	}

	file, err := fileHeader.Open()
	if err != nil {
		ReturnError(c, g.ErrFileReceive, err)
		return
	}
	defer file.Close()
	archiveBytes, err := io.ReadAll(io.LimitReader(file, maxFeishuArchiveSize+1))
	if err != nil || len(archiveBytes) > maxFeishuArchiveSize {
		ReturnError(c, g.ErrFileReceive, "读取 ZIP 文件失败或文件过大")
		return
	}

	articleContent, markdownPath, files, err := readFeishuArchive(archiveBytes)
	if err != nil {
		ReturnError(c, g.ErrFileReceive, err)
		return
	}

	content, failures, uploadedCount := replaceArchiveImages(articleContent, markdownPath, files)
	auth, _ := CurrentUserAuth(c)
	db := GetDB(c)
	article := model.Article{
		Title: title, Content: content, Status: model.STATUS_DRAFT,
		Type: model.TYPE_ORIGINAL, UserId: auth.ID,
		Img: model.GetValueByKey(db, g.CONFIG_ARTICLE_COVER),
	}
	if err = model.SvaeOrUpdateArticle(db, &article, categoryName, tagNames); err != nil {
		ReturnError(c, g.ErrDbOp, err)
		return
	}

	ReturnSuccess(c, feishuImportResult{ArticleID: article.ID, FailedImages: failures, UploadedImages: uploadedCount})
}

func readFeishuArchive(archiveBytes []byte) (string, string, map[string]*zip.File, error) {
	reader, err := zip.NewReader(bytes.NewReader(archiveBytes), int64(len(archiveBytes)))
	if err != nil {
		return "", "", nil, errors.New("无法解析 ZIP 文件")
	}
	if len(reader.File) > maxFeishuArchiveFiles {
		return "", "", nil, fmt.Errorf("ZIP 文件数量不能超过 %d", maxFeishuArchiveFiles)
	}

	files := make(map[string]*zip.File, len(reader.File))
	markdownPaths := make([]string, 0, 1)
	var totalUncompressed uint64
	for _, file := range reader.File {
		filePath, safe := cleanArchivePath(file.Name)
		if !safe {
			return "", "", nil, fmt.Errorf("ZIP 包含不安全的文件路径: %s", file.Name)
		}
		totalUncompressed += file.UncompressedSize64
		if totalUncompressed > maxFeishuArchiveContent {
			return "", "", nil, fmt.Errorf("ZIP 解压后的内容不能超过 %d MiB", maxFeishuArchiveContent>>20)
		}
		if file.FileInfo().IsDir() {
			continue
		}
		files[filePath] = file
		if strings.EqualFold(path.Ext(filePath), ".md") {
			markdownPaths = append(markdownPaths, filePath)
		}
	}
	if len(markdownPaths) != 1 {
		return "", "", nil, errors.New("ZIP 中必须且只能包含一个 Markdown 文件")
	}

	markdownPath := markdownPaths[0]
	markdownFile := files[markdownPath]
	file, err := markdownFile.Open()
	if err != nil {
		return "", "", nil, fmt.Errorf("无法读取 Markdown 文件: %w", err)
	}
	defer file.Close()
	content, err := io.ReadAll(file)
	if err != nil {
		return "", "", nil, fmt.Errorf("无法读取 Markdown 文件: %w", err)
	}
	return string(content), markdownPath, files, nil
}

func replaceArchiveImages(content, markdownPath string, files map[string]*zip.File) (string, []feishuImportFailure, int) {
	uploadedURLs := map[string]string{}
	failedPaths := map[string]string{}
	imageRoot := path.Dir(markdownPath)

	content = markdownImagePattern.ReplaceAllStringFunc(content, func(markdownImage string) string {
		match := markdownImagePattern.FindStringSubmatch(markdownImage)
		if len(match) < 2 {
			return markdownImage
		}
		archivePath, localImage := archiveImageReference(imageRoot, match[1])
		if !localImage {
			return markdownImage
		}
		if publicURL, ok := uploadedURLs[archivePath]; ok {
			return strings.Replace(markdownImage, match[1], publicURL, 1)
		}
		if _, failed := failedPaths[archivePath]; failed {
			return markdownImage
		}

		archiveFile, exists := files[archivePath]
		if !exists {
			failedPaths[archivePath] = "ZIP 中找不到对应图片"
			return markdownImage
		}
		if _, allowed := archiveImageExtensions[strings.ToLower(path.Ext(archivePath))]; !allowed {
			failedPaths[archivePath] = "仅支持 AVIF、GIF、JPEG、PNG、WebP 图片"
			return markdownImage
		}
		if archiveFile.UncompressedSize64 == 0 || archiveFile.UncompressedSize64 > maxFeishuImportedImageSize {
			failedPaths[archivePath] = "图片大小必须在 0 到 10 MiB 之间"
			return markdownImage
		}

		file, err := archiveFile.Open()
		if err != nil {
			failedPaths[archivePath] = "无法读取图片"
			return markdownImage
		}
		publicURL, _, err := upload.UploadReader(path.Base(archivePath), file)
		file.Close()
		if err != nil {
			failedPaths[archivePath] = "上传到对象存储失败"
			return markdownImage
		}
		uploadedURLs[archivePath] = publicURL
		return strings.Replace(markdownImage, match[1], publicURL, 1)
	})

	failures := make([]feishuImportFailure, 0, len(failedPaths))
	for filePath, reason := range failedPaths {
		failures = append(failures, feishuImportFailure{Path: filePath, Reason: reason})
	}
	sort.Slice(failures, func(i, j int) bool { return failures[i].Path < failures[j].Path })
	return content, failures, len(uploadedURLs)
}

func archiveImageReference(markdownDirectory, reference string) (string, bool) {
	reference = strings.Trim(strings.TrimSpace(reference), "<>")
	parsedURL, err := url.Parse(reference)
	if err != nil || parsedURL.IsAbs() || strings.HasPrefix(reference, "//") || strings.HasPrefix(reference, "/") || strings.HasPrefix(reference, "#") {
		return "", false
	}
	decodedReference, err := url.PathUnescape(reference)
	if err != nil {
		return "", false
	}
	return cleanArchivePath(path.Join(markdownDirectory, decodedReference))
}

func cleanArchivePath(filePath string) (string, bool) {
	filePath = strings.ReplaceAll(filePath, "\\", "/")
	filePath = path.Clean(filePath)
	if filePath == "." || strings.HasPrefix(filePath, "../") || strings.HasPrefix(filePath, "/") {
		return "", false
	}
	return filePath, true
}
